baseURL = 'gauravjoshi1.github.io'
languageCode = 'en-us'
title = 'Tech Thoughts'
theme = 'PaperMod'
ShowShareButtons = true
ShowReadingTime = true

[params.profileMode]
enabled = true
title = "Gaurav Joshi"
subtitle = "Engineering Co-op @ Nokia | CS @ UTD"
imageUrl = "https://media-exp1.licdn.com/dms/image/D5603AQFEjOPmuwhOLA/profile-displayphoto-shrink_400_400/0/1664740293996?e=1672272000&v=beta&t=s5q2hKuFSn5fkxnhckSEcNGIj1C43QschVeNKQyZdYY"
imageTitle = "Picture of Gaurav Joshi"
imageWidth = 200
imageHeight = 200

[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts"

[[params.profileMode.buttons]]
name = "Resume"
url = "/resume.pdf"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/gauravjoshi01/"

[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/gauravjosh01"

[[params.socialIcons]]
name = "Email"
url = "mailto:gaurav.joshi@utdallas.edu"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/gauravjoshi1"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
custom_css = ["css/tl.css"]